if(NOT DEFINED PTX OR NOT DEFINED OUT)
    message(FATAL_ERROR "PTX and OUT must be set")
endif()

file(READ "${PTX}" GAFIME_PTX_TEXT)
file(WRITE "${OUT}" "#ifndef GAFIME_RT_OPTIX_PTX_HPP\n")
file(APPEND "${OUT}" "#define GAFIME_RT_OPTIX_PTX_HPP\n\n")
file(APPEND "${OUT}" "#include <cstddef>\n\n")
file(APPEND "${OUT}" "namespace gafime_cuda_v1 {\n")
file(APPEND "${OUT}" "static constexpr const char kRtOptixPtx[] = R\"GAFIME_PTX(\n")
file(APPEND "${OUT}" "${GAFIME_PTX_TEXT}")
file(APPEND "${OUT}" "\n)GAFIME_PTX\";\n")
file(APPEND "${OUT}" "static constexpr std::size_t kRtOptixPtxSize = sizeof(kRtOptixPtx) - 1u;\n")
file(APPEND "${OUT}" "}  // namespace gafime_cuda_v1\n\n")
file(APPEND "${OUT}" "#endif  // GAFIME_RT_OPTIX_PTX_HPP\n")
