#!/usr/bin/env python3
"""
GAFIME Pipeline Generator

Generates a complete, ready-to-run Python script that integrates GAFIME
into a scikit-learn pipeline for classification or regression tasks.
"""

import argparse
import sys
from pathlib import Path


def generate_pipeline_script(
    task: str,
    data_path: str = None,
    target: str = "target",
    model: str = "auto",
    k: int = 10,
    operator: str = "multiply",
    metric: str = "pearson",
) -> str:
    """Generate a complete pipeline script."""

    # Determine model imports and instantiation
    if model == "auto":
        model = "catboost" if task == "classification" else "catboost"

    model_imports = {
        "logistic": "from sklearn.linear_model import LogisticRegression",
        "random_forest": (
            "from sklearn.ensemble import RandomForestClassifier"
            if task == "classification"
            else "from sklearn.ensemble import RandomForestRegressor"
        ),
        "xgboost": "from xgboost import XGBClassifier" if task == "classification" else "from xgboost import XGBRegressor",
        "catboost": "from catboost import CatBoostClassifier" if task == "classification" else "from catboost import CatBoostRegressor",
    }

    model_constructors = {
        "logistic": "LogisticRegression(max_iter=1000, random_state=42)",
        "random_forest": (
            "RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)"
            if task == "classification"
            else "RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)"
        ),
        "xgboost": (
            "XGBClassifier(n_estimators=200, learning_rate=0.1, random_state=42, use_label_encoder=False, eval_metric='logloss')"
            if task == "classification"
            else "XGBRegressor(n_estimators=200, learning_rate=0.1, random_state=42)"
        ),
        "catboost": (
            "CatBoostClassifier(iterations=200, learning_rate=0.1, random_seed=42, verbose=0)"
            if task == "classification"
            else "CatBoostRegressor(iterations=200, learning_rate=0.1, random_seed=42, verbose=0)"
        ),
    }

    scoring = "roc_auc" if task == "classification" else "r2"
    scoring_name = "AUC-ROC" if task == "classification" else "R-squared"

    model_import = model_imports.get(model, model_imports["catboost"])
    model_constructor = model_constructors.get(model, model_constructors["catboost"])

    # Data loading section
    if data_path:
        ext = Path(data_path).suffix
        if ext == ".parquet":
            data_load = f'''# Load data
import polars as pl

df = pl.read_parquet("{data_path}")
feature_cols = [c for c in df.columns if c != "{target}"]
X = df.select(feature_cols).to_numpy().astype(np.float32)
y = df["{target}"].to_numpy().astype(np.float32)
feature_names = feature_cols
print(f"Loaded {{X.shape[0]}} samples x {{X.shape[1]}} features from {data_path}")'''
        else:
            data_load = f'''# Load data
import pandas as pd

df = pd.read_csv("{data_path}")
feature_cols = [c for c in df.columns if c != "{target}"]
X = df[feature_cols].values.astype(np.float32)
y = df["{target}"].values.astype(np.float32)
feature_names = feature_cols
print(f"Loaded {{X.shape[0]}} samples x {{X.shape[1]}} features from {data_path}")'''
    else:
        data_load = f'''# Generate synthetic data (replace with your own data loading)
n_samples, n_features = 5000, 20
X = np.random.randn(n_samples, n_features).astype(np.float32)
# Plant a signal: target depends on interaction of features 0 and 1
y = (0.7 * X[:, 0] * X[:, 1] + 0.3 * X[:, 2] + 0.1 * np.random.randn(n_samples)).astype(np.float32)
{"y = (y > np.median(y)).astype(np.float32)  # Convert to binary for classification" if task == "classification" else ""}
feature_names = [f"feature_{{i}}" for i in range(n_features)]
print(f"Generated {{X.shape[0]}} samples x {{X.shape[1]}} features (synthetic)")'''

    script = f'''#!/usr/bin/env python3
"""
GAFIME {task.title()} Pipeline
Generated by GAFIME build-pipeline skill

This script:
1. Loads your data
2. Discovers top {k} feature interactions using GAFIME (GPU-accelerated)
3. Trains a {model} model with the augmented features
4. Evaluates with cross-validation
"""

import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import {
    "roc_auc_score, classification_report" if task == "classification"
    else "r2_score, mean_squared_error"
}
{model_import}
from gafime.sklearn import GafimeSelector

# ============================================================================
# 1. DATA LOADING
# ============================================================================

{data_load}

# ============================================================================
# 2. TRAIN/TEST SPLIT
# ============================================================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,
    {"stratify=y" if task == "classification" else ""}
)
print(f"Train: {{X_train.shape[0]}} samples, Test: {{X_test.shape[0]}} samples")

# ============================================================================
# 3. GAFIME PIPELINE
# ============================================================================

# GafimeSelector discovers the top {k} most predictive feature interactions
# during fit() and appends them as new columns during transform()
pipeline = Pipeline([
    ("gafime", GafimeSelector(
        k={k},
        backend="auto",       # Auto-selects CUDA > Metal > CPU > NumPy
        metric="{metric}",
        operator="{operator}",
    )),
    ("scaler", StandardScaler()),
    ("model", {model_constructor}),
])

# ============================================================================
# 4. CROSS-VALIDATION
# ============================================================================

print("\\nRunning 5-fold cross-validation...")
cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring="{scoring}")
print(f"  {scoring_name} scores: {{cv_scores}}")
print(f"  Mean {scoring_name}: {{cv_scores.mean():.4f}} (+/- {{cv_scores.std():.4f}})")

# ============================================================================
# 5. FINAL TRAINING & EVALUATION
# ============================================================================

print("\\nTraining final model on full training set...")
pipeline.fit(X_train, y_train)

# Get GAFIME's discovered interactions
gafime_step = pipeline.named_steps["gafime"]
print(f"\\nGAFIME discovered {{len(gafime_step.top_interactions_)}} interactions:")
for i, (feat_i, feat_j) in enumerate(gafime_step.top_interactions_):
    feat_name_i = feature_names[feat_i] if feat_i < len(feature_names) else f"f{{feat_i}}"
    feat_name_j = feature_names[feat_j] if feat_j < len(feature_names) else f"f{{feat_j}}"
    print(f"  {{i+1}}. {{feat_name_i}} {operator} {{feat_name_j}}")

# Evaluate on test set
{"y_pred_proba = pipeline.predict_proba(X_test)[:, 1]" if task == "classification" else ""}
y_pred = pipeline.predict(X_test)

print("\\n" + "=" * 60)
print("TEST SET RESULTS")
print("=" * 60)
{"print(f'AUC-ROC: {roc_auc_score(y_test, y_pred_proba):.4f}')" if task == "classification" else "print(f'R-squared: {r2_score(y_test, y_pred):.4f}')"}
{"print(classification_report(y_test, y_pred))" if task == "classification" else "print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}')"}

# ============================================================================
# 6. COMPARISON: WITH vs WITHOUT GAFIME
# ============================================================================

print("\\n" + "=" * 60)
print("COMPARISON: With vs Without GAFIME Features")
print("=" * 60)

# Baseline model without GAFIME
baseline_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", {model_constructor}),
])
baseline_scores = cross_val_score(baseline_pipeline, X_train, y_train, cv=5, scoring="{scoring}")
print(f"  Without GAFIME: Mean {scoring_name} = {{baseline_scores.mean():.4f}} (+/- {{baseline_scores.std():.4f}})")
print(f"  With GAFIME:    Mean {scoring_name} = {{cv_scores.mean():.4f}} (+/- {{cv_scores.std():.4f}})")
improvement = cv_scores.mean() - baseline_scores.mean()
print(f"  Improvement:    {{'+' if improvement > 0 else ''}}{{improvement:.4f}}")
'''

    return script


def main():
    parser = argparse.ArgumentParser(description="GAFIME Pipeline Generator")
    parser.add_argument("--task", choices=["classification", "regression"], default="classification")
    parser.add_argument("--data", help="Path to CSV or Parquet file", default=None)
    parser.add_argument("--target", default="target", help="Target column name")
    parser.add_argument("--model", default="auto", choices=["auto", "logistic", "random_forest", "xgboost", "catboost"])
    parser.add_argument("--k", type=int, default=10, help="Number of top interactions")
    parser.add_argument("--operator", default="multiply", choices=["multiply", "add", "subtract", "divide"])
    parser.add_argument("--metric", default="pearson", choices=["pearson", "spearman", "r2"])
    parser.add_argument("--output", "-o", default="gafime_pipeline.py", help="Output script path")
    args = parser.parse_args()

    script = generate_pipeline_script(
        task=args.task,
        data_path=args.data,
        target=args.target,
        model=args.model,
        k=args.k,
        operator=args.operator,
        metric=args.metric,
    )

    output_path = Path(args.output)
    output_path.write_text(script, encoding="utf-8")
    print(f"Pipeline script generated: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
