[package]
name = "gafime-cpu"
version.workspace = true
description = "Rust CPU execution backend for GAFIME v1"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
gafime-orchestrator = { path = "../gafime-orchestrator" }
gafime-types = { path = "../gafime-types" }
